### ISSUE TITLE
About the codalab competition website

### ISSUE THREAD

**Issue by 0215Arthur** [msnews/msnews.github.io#11]
Hi 
    I'm very interested in this news recommendation competition.
    I cannot open the codalab competition website via the Chinese IP, even use the VPN proxy .
    Does it have an IP blacklist?

**Comment by wuch15** [comment]
> Hi
> I'm very interested in this news recommendation competition.
> I cannot open the codalab competition website via the Chinese IP, even use the VPN proxy .
> Does it have an IP blacklist?

I also find the codalab website does not work now. You can visit this website later. If you still have some problems in visiting the website, you may try another proxy tool.

**Comment by 0215Arthur** [comment]
> > Hi
> > I'm very interested in this news recommendation competition.
> > I cannot open the codalab competition website via the Chinese IP, even use the VPN proxy .
> > Does it have an IP blacklist?
> 
> I also find the codalab website does not work now. You can visit this website later. If you still have some problems in visiting the website, you may try another proxy tool.

ok, I can visit the competition website Today. Thank you.
