### ISSUE TITLE
behaviors.tsv just has 4 columns

### ISSUE THREAD

**Issue by qqpu** [msnews/msnews.github.io#12]
I noticed the 'behaviors.tsv' just has four columns while it was described as five columns in 'introduction.md'. Could you fix the missing "Impression ID" column? Thanks.

**Comment by yjw1029** [comment]
I checked current behaviors.tsv files in both MIND_small and MIND_large, and not find the issue. 
Can you redownload the dataset from [https://msnews.github.io/](https://msnews.github.io/)? 
We currently update the dataset and its description. If you still notice this issue, could you please offer the address you download the dataset, the specific file names and line numbers? We will fix the issue ASAP.

**Comment by qqpu** [comment]
OK, I redownload the data and now have this column. The reason might be that I download an early version dataset.
