### ISSUE TITLE
How to get the triplets of KG

### ISSUE THREAD

**Issue by 0215Arthur** [msnews/msnews.github.io#15]
The dataset provides the vec file of KG entities and relations, they are very useful. However, the triplets are more important when using KG. So, could you share the basic triplets(wikidata) of MIND?

Thank you very much.

**Comment by Veason-silverbullet** [comment]
I also think the KG file is missing. Could you please share the KG file? @wuch15

**Comment by danyang-liu** [comment]
you can find a kg file here: https://mind201910.blob.core.windows.net/knowledge-graph/wikidata-graph.zip , the graph of wikidata will be updated, you can also download the latest wikidata graph and extract a subgraph for your own usage.

**Comment by Young-vi** [comment]
> you can find a kg file here: https://mind201910.blob.core.windows.net/knowledge-graph/wikidata-graph.zip , the graph of wikidata will be updated, you can also download the latest wikidata graph and extract a subgraph for your own usage.

I can not successfully download this kg file，could you share one of other wikidata-graph files? @danyang-liu

**Comment by aar0npal** [comment]
> you can find a kg file here: https://mind201910.blob.core.windows.net/knowledge-graph/wikidata-graph.zip , the graph of wikidata will be updated, you can also download the latest wikidata graph and extract a subgraph for your own usage.

```
<Error>
   <Code>PublicAccessNotPermitted</Code>
   <Message>Public access is not permitted on this storage account. RequestId:de8434b1-001e-0098-3e46-1a8896000000 Time:2023-11-18T17:39:25.1568959Z</Message>
</Error>
```

I can't access it, any updates on this?
