### ISSUE TITLE
Type of entity in dataset

### ISSUE THREAD

**Issue by sh0416** [msnews/msnews.github.io#16]
Hi,

I wonder what is the type of entity in the dataset.

The description tells us just "the type of entity in wikidata", but I couldn't figure it out.

In wikidata, the type of entity is either "item" or "property", but in this dataset, the type of entity is a single character ranging from "A" to "Z.

Is there anyone who understands this meaning? Just a single URL related to this one will be helpful :)

Thanks,

**Comment by danyang-liu** [comment]
sorry, the type of entity is not the type of entity in wikidata, this is a mistake, here are the type meanings, thanks!

A and   B | Abstraction   (such as disease names)
C | Concept
D | Disambiguation   page in Wikipedia (not an entity)
E | Event
F | Facility   (it could play the role of a location or organization depending of context)
G | Geo-political   entity (such as country, state)
J | Brand   name
L | Location   (such as mountains, rivers, celestial objects)
M and   N | Media   (newspapers, TV and radio stations and programs) / I cannot find info on the   differences between the two labels
O | Organization
P | Person
R | Fictional   character (including deities)
S | Structure   (such as railways, bridges)
T | Other   entities (proper names)
U | Unknown   (no entity type could be assigned based on Wikipedia info)
V | Vehicle   (e.g.: aircraft, ship, automobile)
W | Work   of art (e.g.: book, album, painting, sculpture)
Z | Sport   season / championship

**Comment by sh0416** [comment]
Thanks for the reply. I will consider it 👍
