### ISSUE TITLE
Question on the dataset format

### ISSUE THREAD

**Issue by ghost** [msnews/msnews.github.io#19]
Hi,
The dataset description said that the 'userClickHistory' is all the 'news' that the user has clicked.
So, why it  is not updated sequentially ,
all the 'userClickHistory' by the same user(if the user has more than on row) are all the same.
thanks

**Comment by yjw1029** [comment]
Hi, @MPADAB . It is designed for MIND competition. If we update 'userClickHistory' sequentially, then it is able to infer the click label from 'userClickHistory' of future impressions.
