### ISSUE TITLE
Q: is the click history ordered in chronological or inverse chronological order?

### ISSUE THREAD

**Issue by bluebalam** [msnews/msnews.github.io#20]
In the description of the dataset it reads:

`History. The news click history (ID list of clicked news) of this user before this impression. The clicked news articles are ordered by time.` 

are the oldest or most recent news ids appearing first? For example, given the line:

`N37780 N8541 N81937 N15638 N47169 N23596 N86567 N73301`

is `N37780` the oldest or the newest click?

Thanks!

**Comment by WDdeBWT** [comment]
I have the same question about that. Have you got the conclusion? thanks!

**Comment by yjw1029** [comment]
Hi. In MIND dataset, the oldest news ids appear first.
