### ISSUE TITLE
the order of history attribute in behaviours file

### ISSUE THREAD

**Issue by ruanqin0706** [msnews/msnews.github.io#5]
Hey, Thanks for collecting this awesome news dataset.

I am wondering if news clicks follow the ascending time order, or they are random sequences? 

For example. we assume that User U131 has historic news clicks: N11 N21 N103. Is the time of clicked N11 is earlier than the time of clicked N21.

Thanks in advanced.

**Comment by yusanshi** [comment]
Yes. 

In the paper [*MIND: A Large-scale Dataset for News Recommendation*](https://msnews.github.io/assets/doc/ACL2020_MIND.pdf).
> ClickHist is an ID list of the news articles previously clicked by this user (sorted by click time)


![image](https://user-images.githubusercontent.com/36265606/86871295-91511580-c10c-11ea-8b53-edd2e1fc0631.png)
