### ISSUE TITLE
the order of impressions in behaviour file.

### ISSUE THREAD

**Issue by ruanqin0706** [msnews/msnews.github.io#8]
Hey~
The definition of impressions in [MIND paper](https://msnews.github.io/assets/doc/ACL2020_MIND.pdf) is:  

<img width="412" alt="image" src="https://user-images.githubusercontent.com/15666856/87439168-5c4f3200-c5e8-11ea-8d3e-09d5c5433224.png">

An example is shown as below:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/15666856/87440189-9c62e480-c5e9-11ea-8009-d8f2ab7a0af5.png">

I am wondering if this impressions sequence follows the order that user has seen? (eg, user U131 see N4 earlier than N34). Or it has been re-ordered by whether it was clicked (I noticed clicked news always ahead of non-clicked news)?

Many Thanks.
Qin

**Comment by wuch15** [comment]
Dear Qin, 

Thank you for your interest. In our current dataset, the orders of news articles in an impression have been shuffled. Thus, clicked news may not always appear ahead of non-clicked news.

Best,
Chuhan

**Comment by q710245300** [comment]
Hi,

Can you publish a dataset which the impression is ordered? Or the orginal user impression logs.Thank you very much.

Best,
YuYan

**Comment by wuch15** [comment]
Hi Yuyan,

The historical clicked news articles of users are in time order. In the current dataset, we do not include the raw impression logs that are used for building user history and they might be released if necessary. For the impression logs that are used for building labeled samples, you can aggregate those from the same user and order them by time. 

Best, 
Chuhan

**Comment by ruanqin0706** [comment]
> Dear Qin,
> 
> Thank you for your interest. In our current dataset, the orders of news articles in an impression have been shuffled. Thus, clicked news may not always appear ahead of non-clicked news.
> 
> Best,
> Chuhan

Thank you so much !
